workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    environment:
      flutter: 3.22.2
      xcode: latest
      vars:
        CM_KEYSTORE: /tmp/keystore.jks
        CM_KEYSTORE_PASSWORD: Bigfun@2580
        CM_KEY_ALIAS: bigfun
        CM_KEY_PASSWORD: Bigfun@2580
    scripts:
      - name: Clean project
        script: |
          flutter clean
          rm -rf android/.gradle
      - name: Get dependencies
        script: flutter pub get
      - name: Build APK
        script: |
          cd android
          ./gradlew clean
          cd ..
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
