name: Flutter Build (Full Signed APK + AAB)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # Decode keystore
      - name: Decode keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > android/app/my-release-key.jks

      # Create key.properties
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=my-release-key.jks" >> android/key.properties

      # Decode google-services.json
      - name: Decode google-services.json
        env:
          GSJSON: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
        run: |
          echo "$GSJSON" | base64 --decode > android/app/google-services.json

      # Save Agora secrets into config file
      - name: Write Agora config
        run: |
          mkdir -p lib/config
          echo "class AgoraConfig {" > lib/config/agora_config.dart
          echo "  static const String appId = '${{ secrets.AGORA_APP_ID }}';" >> lib/config/agora_config.dart
          echo "  static const String certificate = '${{ secrets.AGORA_APP_CERTIFICATE }}';" >> lib/config/agora_config.dart
          echo "}" >> lib/config/agora_config.dart

      # Decode Parvez file (if needed)
      - name: Decode Parvez file
        if: ${{ secrets.PARVEZ_FILE_BASE64 != '' }}
        env:
          PARVEZ_FILE_BASE64: ${{ secrets.PARVEZ_FILE_BASE64 }}
        run: |
          echo "$PARVEZ_FILE_BASE64" | base64 --decode > lib/config/parvez.dart

      # Build APK
      - name: Build APK (release)
        run: flutter build apk --release

      # Build AAB
      - name: Build AAB (release)
        run: flutter build appbundle --release

      # Upload APK
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # Upload AAB
      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
