name: Flutter Build (Full Signed APK + AAB)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 3) Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4) Decode keystore
      - name: Decode keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > android/app/my-release-key.jks

      # 5) Create key.properties
      - name: Create key.properties
        run: |
          echo "storePassword=Bigfun@2580" >> android/key.properties
          echo "keyPassword=Bigfun@2580" >> android/key.properties
          echo "keyAlias=bigfun" >> android/key.properties
          echo "storeFile=my-release-key.jks" >> android/key.properties

      # 6) Decode google-services.json
      - name: Decode google-services.json
        env:
          GSJSON: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
        run: |
          echo "$GSJSON" | base64 --decode > android/app/google-services.json

      # 7) Build APK (release)
      - name: Build APK (release)
        run: flutter build apk --release

      # 8) Build AAB (release)
      - name: Build AAB (release)
        run: flutter build appbundle --release

      # 9) Upload APK
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # 10) Upload AAB
      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab
